import { SidenavMenu } from './sidenav-menu.model';

export const sidenavMenuItems = [ 
    new SidenavMenu (1, 'Home', '/', null, null, false, 0),
    new SidenavMenu (2, 'top brandsof laptops', null, null, null, true, 0), 
    new SidenavMenu (10, 'Lenovo', null, null, null, true, 2),   
    new SidenavMenu (11, 'Lenovo ideapad 320', '/products/Lenovo ideapad 320', null, null, false, 10),
    new SidenavMenu (12, 'Lenovo ideapad', '/products/Lenovo ideapad', null, null, false, 10),
    new SidenavMenu (13, 'Lenovo Yoga 720', '/products/Lenovo Yoga 720', null, null, false, 10), 
    new SidenavMenu (14, 'Lenovo Thinkpad X1 Carbon', '/products/Lenovo Thinkpad', null, null, false, 10), 
    new SidenavMenu (15, 'Lenovo Miix 320', '/products/Lenovo Miix 320', null, null, false, 10), 
    new SidenavMenu (20, 'Dell', null, null, null, true, 2),  
    new SidenavMenu (21, 'Dell XPS 13', '/products/Dell XPS 13', null, null, false, 20),
    new SidenavMenu (22, 'Alienware 17 R5', '/products/Alienware 17 R5', null, null, false, 20),
    new SidenavMenu (23, 'Dell Precision %%30', '/products/Dell Precision %%30', null, null, false, 20),
    new SidenavMenu (24, 'sony', '/products/sony', null, null, false, 20),
    new SidenavMenu (30, 'Apple', null, null, null, true, 2), 
    new SidenavMenu (31, 'IMac', '/products/IMac', null, null, false, 30),
    new SidenavMenu (32, 'MacBook Pro', '/products/MacBook Pro', null, null, false, 30),
    new SidenavMenu (33, 'Imac MacBook', '/products/Imac MacBook', null, null, false, 30),
    new SidenavMenu (34, 'MacBook(2017)', '/products/MacBook(2017)', null, null, false, 30),
    new SidenavMenu (35, 'MacBook', '/products/MacBook', null, null, false, 30),
    new SidenavMenu (40, 'Acer', null, null, null, true, 2), 
    new SidenavMenu (41, 'Acer', '/products/Acer', null, null, false, 40),
    new SidenavMenu (42, 'Acer', '/products/Acer', null, null, false, 40),
    new SidenavMenu (43, 'Acer', '/products/Acer', null, null, false, 40),
    new SidenavMenu (44, 'Acer', '/products/Acer', null, null, false, 40),
    new SidenavMenu (50, 'aser', '/products/aser', null, null, false, 0), 
    new SidenavMenu (51, 'samsung', '/products/samsung', null, null, false, 0), 
    new SidenavMenu (52, 'sony', '/products/sony', null, null, false, 0),
    new SidenavMenu (52, 'vu', '/products/vu', null, null, false, 0),
    new SidenavMenu (60, 'Pages', null, null, null, true, 0), 
    new SidenavMenu (61, 'All products', '/products', null, null, false, 60), 
    new SidenavMenu (62, 'Product detail', '/products/2/PC All-in-One', null, null, false, 60), 
    new SidenavMenu (63, 'Sign in', '/sign-in', null, null, false, 60), 
    new SidenavMenu (64, '404 Error', '/404', null, null, false, 60), 
    new SidenavMenu (80, 'Contact', '/contact', null, null, false, 0),  
    new SidenavMenu (140, 'Level 1', null, null, null, true, 0),
    new SidenavMenu (141, 'Level 2', null, null, null, true, 140),
    new SidenavMenu (142, 'Level 3', null, null, null, true, 141),
    new SidenavMenu (143, 'Level 4', null, null, null, true, 142),
    new SidenavMenu (144, 'Level 5', null, 'http://themeseason.com', null, false, 143),
    new SidenavMenu (200, 'External Link', null, 'http://themeseason.com', '_blank', false, 0)
]